Mokuton:
  item01:
    nome: ''
    id: 0
  item02:
    nome: ''
    id: 0
  item03:
    nome: ''
    id: 0

####################

Bakuton:
  item01:
    nome: ''
    id: 0
  item02:
    nome: ''
    id: 0
  item03:
    nome: ''
    id: 0

####################

Shoton:
  item01:
    nome: ''
    id: 0
  item02:
    nome: ''
    id: 0
  item03:
    nome: ''
    id: 0

####################

Hyoton:
  item01:
    nome: ''
    id: 0
  item02:
    nome: ''
    id: 0
  item03:
    nome: ''
    id: 0

####################

Ranton:
  item01:
    nome: ''
    id: 0
  item02:
    nome: ''
    id: 0
  item03:
    nome: ''
    id: 0